# Jupyter, ipython, etc.
export PATH="$HOME/.local/bin:$PATH"

export PATH="$HOME/.pyenv/bin:$PATH"

# Brew binaries.
eval "$(/opt/homebrew/bin/brew shellenv 2>/dev/null)"

# Golang
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

# LANG
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Include other configs.
if [ -f ~/.bash_aliases ]; then
  source $HOME/.bash_aliases;
fi
if type bind &> /dev/null; then
  bind -f $HOME/.inputrc;
  fi

for config in $HOME/.bash_configs.d/*; do
  if [ -r $config ] ; then source $config; fi
done
