# Jupyter, ipython, etc.
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.pyenv/bin:$PATH"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

if type bind &> /dev/null; then
  bind -f $HOME/.inputrc;
fi

for config in $HOME/.bash_configs.d/*; do
  if [ -r $config ] ; then source $config; fi
done
