- name: Setup | system
  hosts: '{{ target_host | default("localhost") }}'
  roles:
    - role: system
      when: setup_system | default(false) | bool
    - role: vim
      when: setup_system | default(false) | bool

- name: Setup | vim
  hosts: '{{ target_host | default("localhost") }}'
  roles:
    - role: vim
      when: setup_vim | default(false) | bool

- name: Setup | scribe
  hosts: '{{ target_host | default("localhost") }}'
  roles:
    - role: scribe
      when: setup_scribe | default(false) | bool
