#!/bin/bash
set -x

if [[ "`uname -s`" == "Darwin" ]]; then
  brew tap universal-ctags/universal-ctags
  brew install --HEAD universal-ctags
  # Bat supports syntax highlighting for a large number
  # of programming and markup languages.
  # Fzf uses bat for preview windows.
  brew install bat
fi

rm -rf ~/.vim && curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +quitall
