#!/bin/bash
set -x

if [[ "`uname -s`" == "Linux" ]]; then
  # $1 - src dir
  # $2 - install dir
  build() {
    pushd $1
    for s in ./autogen.sh ./configure
    do
      if [[ -f $s ]]; then $s; fi
    done

    if [[ -f ./Makefile ]]; then
      make
      fakeroot make install DESTDIR=$2
    fi
    popd
  }

  # $1 - src directory
  # $2 - pkg name
  # $3 - pkg description
  package_build() {
    pushd $1
    if [[ `which dpkg` ]]; then
      mkdir -v DEBIAN
      find etc 2>/dev/null | sed "s/^/\//" > DEBIAN/conffiles
      ARCH=`dpkg --print-architecture`
      echo "\
Package: $2
Version: 0.0.1
Architecture: ${ARCH}
Maintainer: smb
Description: $3
" > DEBIAN/control
    fi
    popd

    if [[ `which dpkg` ]]; then
      dpkg -b $1 $2.deb
    fi
  }

  package_install() {
    if [[ `which dpkg` ]]; then
      sudo dpkg -i $1.deb
    fi
  }

  install_git_repo() {
    TEMP_DIR=`mktemp -d -t $(date +%Y-%m-%d-%H-%M-%S)-XXXXXXXX`
    pushd ${TEMP_DIR}
    git clone $1
    PROJECT_NAME=`ls`
    cd ${PROJECT_NAME}
    PACKAGE_ROOT_DIR=`pwd`/${PROJECT_NAME}_$(date +%Y-%m-%d-%H-%M-%S)
    build `pwd` ${PACKAGE_ROOT_DIR}
    package_build ${PACKAGE_ROOT_DIR} ${PROJECT_NAME} $1
    package_install ${PROJECT_NAME}
    popd
    rm -rf $TEMP_DIR
  }

  sudo apt install -y \
    autoconf          \
    automake          \
    autotools-dev     \
    fakeroot          \
    libtool           \
    make              \
    pkg-config

  install_git_repo https://github.com/universal-ctags/ctags.git
fi
