#!/bin/bash
set -x

function show_help {
  echo "help"
}

ANSIBLE_EXTRA_VARS=()
POS_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      show_help
      exit 0
      ;;

    -h=*|--host=*)
      ANSIBLE_EXTRA_VARS+=("target_host=${1#*=}")
      shift
      ;;

    -u|--upgrade)
      ANSIBLE_EXTRA_VARS+=("update_repo_cache=1" "upgrade_packages=1")
      shift
      ;;

    --update)
      ANSIBLE_EXTRA_VARS+=("update_repo_cache=1")
      shift
      ;;

    *)
      POS_ARGS+=("$1")
      shift
      ;;
  esac
done

if [ `uname` == "Darwin" ]; then
  # homebrew
  # homebrew_tap
  ansible-galaxy collection install community.general
fi

for i in ${POS_ARGS[@]}; do
  ANSIBLE_EXTRA_VARS+=("setup_${i}=1")
done

ansible-playbook -i hosts ${ANSIBLE_EXTRA_VARS[@]/#/--extra-vars\ } setup.yml
