#!/bin/bash
set -x

if [[ "`uname -s`" == "Linux" ]]; then
  install_git_repo() {
    TEMP_DIR=`mktemp -d -t $(date +%Y-%m-%d-%H-%M-%S)-XXXXXXXX`
    pushd ${TEMP_DIR}
    git clone $1
    PROJECT_NAME=`ls`
    cd ${PROJECT_NAME}
    PACKAGE_ROOT_DIR=`pwd`/${PROJECT_NAME}_$(date +%Y-%m-%d-%H-%M-%S)

    # Building
    for s in ./autogen.sh ./configure ./build.sh
    do
      if [[ -f $s ]]; then $s; fi
    done

    if [[ -f ./Makefile ]]; then
      make
    fi

    # Installation
    if [[ -f ./Makefile ]]; then
      sudo make install
    fi

    popd
    rm -rf $TEMP_DIR
  }

  install_git_repo https://github.com/universal-ctags/ctags.git

  sudo yum install -y pcre-devel xz-devel
  install_git_repo https://github.com/ggreer/the_silver_searcher.git
fi
