#!/bin/bash
set -x

if [[ "`uname -s`" == "Linux" ]]; then
  # $1 - src dir
  # $2 - install dir
  build() {
    pushd $1
    for s in ./autogen.sh ./configure
    do
      if [[ -f $s ]]; then $s; fi
    done

    if [[ -f ./Makefile ]]; then
      make
    fi
    popd
  }

  # $1 - src directory
  # $2 - pkg name
  # $3 - pkg description
  package_build() {
    :
  }

  package_install() {
    :
  }

  install_git_repo() {
    TEMP_DIR=`mktemp -d -t $(date +%Y-%m-%d-%H-%M-%S)-XXXXXXXX`
    pushd ${TEMP_DIR}
    git clone $1
    PROJECT_NAME=`ls`
    cd ${PROJECT_NAME}
    PACKAGE_ROOT_DIR=`pwd`/${PROJECT_NAME}_$(date +%Y-%m-%d-%H-%M-%S)
    build `pwd` ${PACKAGE_ROOT_DIR}
    package_build ${PACKAGE_ROOT_DIR} ${PROJECT_NAME} $1
    package_install ${PROJECT_NAME}
    popd
    rm -rf $TEMP_DIR
  }

  install_git_repo https://github.com/universal-ctags/ctags.git
fi


rm -rf ~/.vim && curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +quitall
