- name: setup_vms | create /var/lib/libvirt/images/* directories
  file:
    path: "/var/lib/libvirt/images/{{ item.name }}"
    mode: "644"
    state: directory
    recurse: yes
  become: yes
  with_items: "{{ vms }}"

- name: setup_vms | install /var/lib/libvirt/images/*/*
  template:
    src: "{{ item[1] }}.j2"
    dest: "/var/lib/libvirt/images/{{item[0].name}}/{{ item[1] }}"
    mode: "664"
  become: yes
  with_nested:
    - "{{ vms }}"
    - [ "meta-data", "user-data" ]
