- import_tasks: debian.yml
  become: yes
  when: ansible_os_family == "Debian"

- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- import_tasks: centos.yml
  become: yes
  when: ansible_os_family == "RedHat"
