- import_tasks: os_debian.yml
  become: yes
  when: ansible_os_family == "Debian"

- import_tasks: os_darwin.yml
  when: ansible_os_family == "Darwin"

- import_tasks: os_centos.yml
  become: yes
  when: ansible_os_family == "RedHat"
