- name: system [centos] | update repositories cache
  yum: update_cache=yes
  changed_when: False
  when: update_repo_cache | default(false) | bool

- name: system [centos] | upgrade out of date packages, excluding kernel
  yum:
    name: '*'
    state: latest
    exclude: kernel*
  when: upgrade_packages | default(false) | bool

- name: system [centos] | install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: system [centos] | install requirements
  package: name="{{ item.value }}"
  with_dict: "{{ system_requirements_centos }}"
