Vagrant.configure("2") do |config|
  config.vm.define :mdev do |mdev|
    mdev.vm.box = "generic/ubuntu1804"

    mdev.vm.provider "libvirt" do |vm|
      vm.cpus = 24
      vm.memory = 30 * 1024
      vm.graphics_type = "none"
    end
  end

  config.vm.synced_folder "../", "/home/vagrant/Projects/mydev"
end
