- name: setup_system | create ~/.* directories
  file:
    path: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "744"
    state: directory
    recurse: yes
  with_items:
    - bash_configs.d

- name: setup_system | install $HOME/.*
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "644"
  with_items:
    - bash_configs.d/bash.sh
    - bash_configs.d/kubernetes.sh
    - bash_configs.d/python.sh
    - bash_configs.d/yandex.sh
    - bash_aliases
    - bash_profile
    - bashrc
    - inputrc
    - tmux.conf

- import_tasks: configs_debian.yml
  when: ansible_os_family == "Debian"
