vim_requirements_debian:
  - flake8
  - pylint
  - vim
  - silversearcher-ag
  - yapf3

vim_requirements_darwin:
  - flake8
  - pylint
  - vim
  - the_silver_searcher
  - yapf

  # brew tap universal-ctags/universal-ctags
  # brew install universal-ctags
  - universal-ctags

  # Bat supports syntax highlighting for a large number
  # of programming and markup languages.
  # Fzf uses bat for preview windows.
  - bat

vim_requirements_centos:
  - vim
