- name: system [darwin] | install requirements [system]
  package: name="{{ item }}"
  with_items: "{{ system_requirements }}"

- name: system [darwin] | install requirements [python]
  package: name="{{ item }}"
  with_items: "{{ python_requirements + python_requirements_darwin }}"

- name: system [darwin] | install requirements [vim]
  package: name="{{ item }}"
  with_items: "{{ vim_requirements_darwin }}"
