- name: system | create ~/.* directories
  file:
    path: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "744"
    state: directory
    recurse: yes
  with_items:
    - bash_configs.d

- name: system | install $HOME/.*
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "644"
  with_items:
    - bash_configs.d/bash
    - bash_configs.d/ghcup
    - bash_configs.d/git
    - bash_configs.d/golang
    - bash_configs.d/kubernetes
    - bash_configs.d/python
    - bash_configs.d/ruby
    - bash_configs.d/yandex
    - bash_aliases
    - bash_profile
    - bashrc
    - inputrc
    - tmux.conf

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
