#!/bin/bash
set -x

source common/include
install_setup

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"
install_ln ${SCRIPT_DIR}/python.conf ~/.python.conf

install curl \
        python3

if ! `python3 -m pip &>/dev/null`; then
  curl https://bootstrap.pypa.io/get-pip.py | python3 -
fi

python3 -m pip install -U pip

python3 -m pip install \
  setuptools \
  wheel

#
# Remote debugging based on pdb.
#

# https://github.com/tamentis/rpdb
python3 -m pip install rpdb
