- name: vim [darwin] | update homebrew
  community.general.homebrew:
    update_homebrew: yes
  when: update_repo_cache | default(false) | bool

- name: vim [darwin] | upgrade out of date packages
  community.general.homebrew:
    upgrade_all: yes
  when: upgrade_packages | default(false) | bool

# brew tap universal-ctags/universal-ctags
# brew install universal-ctags
- name: vim [darwin] | tap a homebrew universal-ctags/universal-ctags repository
  community.general.homebrew_tap:
    name: universal-ctags/universal-ctags

- name: vim [darwin] | install requirements
  package: name="{{ item.value }}"
  with_dict: "{{ vim_requirements_darwin }}"
