# Jupyter, ipython, etc.
export PATH="$HOME/.local/bin:$PATH"

export PATH="$HOME/.pyenv/bin:$PATH"

# Brew binaries.
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/opt/curl/bin:$PATH"
export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
export PATH="/usr/local/opt/python@3.7/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH"

# Golang
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

# LANG
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Include other configs.
if [ -f ~/.bash_aliases ]; then . ~/.bash_aliases; fi
if type bind &> /dev/null; then bind -f ~/.inputrc; fi
for config in $HOME/.bash_configs.d/*.sh; do
  if [ -r $config ] ; then . $config; fi
done
