- name: vim [debian] | update repositories cache [apt]
  apt: update_cache=yes
  changed_when: False

- name: vim [debian] | upgrade out of date packages [apt]
  apt: upgrade=safe

- name: vim [debian] | install requirements [vim]
  package: name="{{ item }}"
  with_items: "{{ vim_requirements_debian }}"
