ansible_requirements_debian:
  - aptitude
  - python3
  - python3-apt
  - python3-pexpect
  - python3-pip

system_requirements:
  - curl
  - tmux
  - telnet
  - git

system_requirements_debian:
  # Allow apt to use a repository over HTTPS.
  - apt-transport-https
  - ca-certificates
  - gnupg2

  # System tools.
  - locales
  - lsb-release
  - software-properties-common

  # Build tools.
  - autoconf
  - automake
  - autotools-dev
  - binutils
  - gcc
  - g++
  - make
  - pkg-config
  - sed

system_requirements_centos:
  # System tools.
  - redhat-lsb

python_requirements:
  - python3

python_requirements_debian:
  - python3-apt

  # Development.
  - python3-pip
  - python3-venv
  - tox
  - rlwrap

  # Build dependencies.
  - build-essential
  - gcc
  - libffi-dev
  - libssl-dev
  - python3-dev

  # To build python with pyevn.
  - libbz2-dev
  - liblzma-dev
  - libreadline-dev
  - libsqlite3-dev

  # To support MySQL.
  - libmysqlclient-dev

python_requirements_darwin:
  # Development.
  - tox
  - rlwrap

python_requirements_centos:
  # Development.
  - python3-pip
