# ansible_requirements_debian:
#   - aptitude
#   - python3
#   - python3-apt
#   - python3-pexpect
#   - python3-pip

system_requirements:
  - curl
  - tmux
  - telnet
  - git
  - expect
  - rlwrap
  - python3

system_requirements_debian:
  # Allow apt to use a repository over HTTPS.
  - apt-transport-https
  - ca-certificates
  - gnupg2

  - locales
  - lsb-release
  - software-properties-common

  - autoconf
  - automake
  - autotools-dev
  - binutils
  - gcc
  - g++
  - make
  - pkg-config
  - sed

#
# Python requirements
# {
  - python3-apt
  - python3-pip
  - python3-venv
  - tox

  # Build dependencies.
  - build-essential
  - gcc
  - libffi-dev
  - libssl-dev
  - python3-dev

  # To build python with pyevn.
  - libbz2-dev
  - liblzma-dev
  - libreadline-dev
  - libsqlite3-dev

  # To support MySQL.
  - libmysqlclient-dev
# }

system_requirements_darwin:
  - tox

system_requirements_centos:
  - redhat-lsb
  - python3-pip
  - python-tox
