ansible_requirements_debian:
  - aptitude
  - git
  - python3
  - python3-apt
  - python3-pexpect
  - python3-pip

system_requirements:
  - curl
  - tmux

system_requirements_debian:
  # Allow apt to use a repository over HTTPS.
  - apt-transport-https
  - ca-certificates
  - gnupg2

  # System tools.
  - locales
  - lsb-release
  - software-properties-common

  # Build tools.
  - autoconf
  - automake
  - autotools-dev
  - binutils
  - gcc
  - g++
  - make
  - pkg-config
  - sed

python_requirements:
  - python3
  - tox

  # To support remote debugging.
  - rlwrap
  - telnet

python_requirements_debian:
  - python3-apt
  - python3-pip
  - python3-venv

  # Build dependencies.
  - build-essential
  - gcc
  - libffi-dev
  - libssl-dev
  - python3-dev

  # To build python with pyevn.
  - libbz2-dev
  - liblzma-dev
  - libreadline-dev
  - libsqlite3-dev

  # To support MySQL.
  - libmysqlclient-dev
